### ISSUE TITLE
systemcheck, filebrowser, playlists on top bar all give error.

### ISSUE THREAD

**Issue by killhellokitty** [othmar52/slimpd#10] opened 2016-07-19 21:55 UTC
OOOPS!

something went wrong...
/slimpd/index.php/filebrowser?null

**Comment by othmar52** [comment] 2016-07-19 22:09
pretty sure this is caused by permissions of your music directory

there should be a link in those "OOOPS"-notifications. please click on this link and add an additional parameter to the url like `?debug`  (or  `&debug` in case a questionmark already exists)

In this specific case: What is the output of `/slimpd/index.php/filebrowser?null&debug` ?

**Comment by killhellokitty** [comment] 2016-07-19 22:22
A completly blank page.  It just goes back to
127.0.0.1/slimpd/index.php/filebrowser
and a blank page.

**Comment by othmar52** [comment] 2016-07-19 22:29
hmmm. can you find any useful hint in the error-log of lighttpd?

**Comment by killhellokitty** [comment] 2016-07-19 22:32
No errors in the lighttpd error-log.  All is well.

**Comment by othmar52** [comment] 2016-07-20 06:38
do you have symlinks in your mpd music directory?
case yes - add the non symlinked path to your configuration (with trailing slash)
```
[mpd]
alternative_musicdir = 
```

further i have added another configuration option
```
[filebrowser]
restrict-to-musicdir = 1
```
set this to ` 0 ` and try to access /filebrowser again.

**Comment by killhellokitty** [comment] 2016-07-21 17:38
I updated and made these additions.  The filebrowser works now, except when
the icon is selected from the nav bar.  The icon still doesn't work.
I moved my music collection to a /media/Music and rebuilt MPD as a global
app.  Systemcheck says everything is working and good now.
It shows most album covers, but not all for some reason.  I'll try to delve
into what is different about the albums that are not showing up.

**Comment by othmar52** [comment] 2016-07-21 18:25
handling playlist is not implemented yet. for now you can only display *.m3u content or append to/replace  mpd's current playlist.
to hide the nav-item at all add this to your config
```
[mainmenu]
3.title = menu.playlists
3.url = 
```

to jump into a specific directory when click on the playlists-nav-item add something like
```
[mainmenu]
3.title = menu.playlists
3.url = filebrowser/path/to/your/playlist-dir/inside/mpd-dir
```
what happens if you click the directory-icon in the navbar?

does "local player" also work?

**Comment by killhellokitty** [comment] 2016-07-21 19:31
When the directory-icon in the navbar is pressed this error popup:
http://127.0.0.1/slimpd/index.php/filebrowser?null
debug message: *Message:* file_exists(): open_basedir restriction in
effect. File(/media/Music/..) is not within the allowed path(s):
(/srv/http/:/home/:/tmp/:/usr/share/pear/:/usr/share/webapps/:/etc/webapps/:/dev/shm/:/media/Music/:/var/lib/mpd/:/usr/bin/)
I don't know how it wants "/media/Music/" to be listed with open_basedir?

And yes 'local player' works.

**Comment by othmar52** [comment] 2016-07-25 06:25
> debug message: *Message:* file_exists(): open_basedir restriction in
> effect. File(/media/Music/..) is not within the allowed path(s):

Now i have read the error message again and recognised those two points `..` which results in a forbidden/restricted call of `file_exists('/media/')`.

Please pull the [latest commit](https://github.com/othmar52/slimpd/commit/e0a4dc719d8e39aee0e430d091dd2f15dd69f635) and try again

**Comment by killhellokitty** [comment] 2016-07-27 19:05
systemcheck and filebrowser are now working without error.  Playlists on top bar is currently not working, still under construction.

**Comment by othmar52** [comment] 2016-09-08 06:32
In the meantime a separate issue #39 for the remaining error had been opened
so i will close this issue...

**Closed by othmar52** 2016-09-08 06:32 UTC
